server:
  port: 8002
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
  server:
    enable-self-preservation: false
zuul:
  routes:
    user-api:
      path: /user-api/**
      serviceId: user-service
spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: zuul-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672