server:
  port: 8776
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8750/eureka/
spring:
  application:
    name: trace-A
  zipkin:
    base-url: http://localhost:9411/