server:
  port: 8765
spring:
  application:
    name: eureka-feign-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8750/eureka/
feign:
  hystrix:
    enabled: true